 artists.html                      |   2 [32m+[m[31m-[m
 artists/adam-beyer.html           |   7 [32m++[m
 artists/adam-port.html            |   6 [32m++[m
 artists/adam-ten.html             |   7 [32m++[m
 artists/adriatique.html           |   7 [32m++[m
 artists/anotr.html                |   7 [32m++[m
 artists/anyma.html                |   7 [32m++[m
 artists/artbat.html               |   7 [32m++[m
 artists/ayybo.html                |   7 [32m++[m
 artists/bedouin.html              |   7 [32m++[m
 artists/biscits.html              |   7 [32m++[m
 artists/black-coffee.html         |   6 [32m++[m
 artists/camelphat.html            |   7 [32m++[m
 artists/chris-lake.html           |   7 [32m++[m
 artists/chris-stussy.html         |   7 [32m++[m
 artists/cloonee.html              |   7 [32m++[m
 artists/dennis-cruz.html          |   6 [32m++[m
 artists/disclosure.html           |   7 [32m++[m
 artists/disco-lines.html          |   7 [32m++[m
 artists/dom-dolla.html            |   7 [32m++[m
 artists/dombresky.html            |   7 [32m++[m
 artists/eats-everything.html      |   7 [32m++[m
 artists/fisher.html               |   7 [32m++[m
 artists/franky-rizardo.html       |   7 [32m++[m
 artists/green-velvet.html         |   7 [32m++[m
 artists/hugel.html                |   7 [32m++[m
 artists/innellea.html             |   7 [32m++[m
 artists/it-s-murph.html           |   7 [32m++[m
 artists/james-hype.html           |   7 [32m++[m
 artists/jamie-jones.html          |   7 [32m++[m
 artists/jamie-xx.html             |   7 [32m++[m
 artists/john-summit.html          |   7 [32m++[m
 artists/joseph-capriati.html      |   7 [32m++[m
 artists/josh-baker.html           |   7 [32m++[m
 artists/keinemusik.html           |   7 [32m++[m
 artists/kolter.html               |   7 [32m++[m
 artists/malaa.html                |   7 [32m++[m
 artists/marco-carola.html         |   6 [32m++[m
 artists/matroda.html              |   7 [32m++[m
 artists/mau-p.html                |   7 [32m++[m
 artists/me.html                   |   6 [32m++[m
 artists/michael-bibi.html         |   6 [32m++[m
 artists/miguel-campbell.html      | 134 [32m++++++++++++++++++++++++++++++++++++++[m
 artists/mita-gami.html            |   6 [32m++[m
 artists/mochakk.html              |   7 [32m++[m
 artists/monolink.html             |   7 [32m++[m
 artists/odd-mob.html              |   7 [32m++[m
 artists/oden-fatzo.html           |   7 [32m++[m
 artists/omri.html                 |   7 [32m++[m
 artists/patrick-topping.html      |   7 [32m++[m
 artists/pawsa.html                |   5 [32m++[m
 artists/peggy-gou.html            |   6 [32m++[m
 artists/purple-disco-machine.html |   7 [32m++[m
 artists/rampa.html                |   5 [32m++[m
 artists/sammy-virji.html          |   7 [32m++[m
 artists/san-pacho.html            |   7 [32m++[m
 artists/seth-troxler.html         |   7 [32m++[m
 artists/sidney-charles.html       |   6 [32m++[m
 artists/solomun.html              |   7 [32m++[m
 artists/stay-golden.html          | 131 [32m+++++++++++++++++++++++++++++++++++++[m
 artists/tchami.html               |   7 [32m++[m
 artists/vintage-culture.html      |   7 [32m++[m
 artists/wade.html                 |   7 [32m++[m
 artists/westend.html              |   7 [32m++[m
 artists/whomadewho.html           |   7 [32m++[m
 friday.html                       |   2 [32m+[m[31m-[m
 index.html                        |  16 [32m++[m[31m---[m
 roster.html                       |   9 [32m+[m[31m--[m
 tours.html                        |   6 [32m+[m[31m-[m
 69 files changed, 704 insertions(+), 17 deletions(-)
